// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tpgngkyhaoodysjtnsxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwZ25na3loYW9vZHlzanRuc3hkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk0NjA5ODksImV4cCI6MjA1NTAzNjk4OX0.Kbj3RsbH1E8sWRaRzhrFXDuYgdGm4bXx9W-YYkD0TE8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);